# Generated by Django 5.2.7 on 2025-11-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Repository", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journey",
            name="client",
        ),
        migrations.AddField(
            model_name="journey",
            name="clients",
            field=models.ManyToManyField(
                related_name="journeys", to="Repository.client"
            ),
        ),
    ]
